### ISSUE TITLE
Create a python module to store topics in ElasticSearch

### ISSUE THREAD

**Issue by eemp** [icwhatuc/auto-quiz-mill#3]
Think about what a topic needs:
- name
- date when the topic was found to be trending
- should the record expire (does ElasticSearch have expiration for records so that they can be automatically deleted?)

Think about what should the elasticsearch record id be?

We want to be able to say something like this in our data scripts that pull topics:

`my $store = "AQM::ElasticSearch";` or

`my $store = "AQM::NoSQL";` or

`my $store = "AQM::SQL";`

then to create or modify existing topic:

`$store->saveTopic(HASH)`

or to delete a topic:

`$store->deleteTopic(HASH)`

Write a module that supports those two general methods in python, test.  Ensure that details of the implementation are not tied to the type of data store we use!  We want to be able to switch out data stores in the future for our scripts easily!

**Comment by hayamikaito** [comment]
https://elasticsearch-py.readthedocs.org/en/master/

**Comment by hayamikaito** [comment]
Wrote the modules for saving and deleting the topic in perl.

**Comment by eemp** [comment]
Done via perl
