### ISSUE TITLE
Come up with a plan to incorporate topics of user interest

### ISSUE THREAD

**Issue by eemp** [icwhatuc/auto-quiz-mill#4]
We want to be able to allow users to specify general topics like "Revolutionary War" and we can have some code that takes this and automatically expands this to entities like:
- "George Washington"
- "Battle of Bunker Hill"
- "Benjamin Franklin"
- "Declaration of Independence"
- "Boston Tea Party"
  etc.

Ultimately, we can just have the user submit a syllabus they might have received from a class, identify general topics with NLP / entity extraction, and expand into further topics as described above.

How can we accomplish something like this?
- libraries, APIs?
- what if we can retrieve top books associated with the topic, then the index in the back of the book would have specific entities (ex: a book on the Revolutionary War would have all those entities mentioned) - is there a book API that return the index with the books?

Essentially, we want to expand upon a general topic or find further closely related topics.

**Comment by mirajp** [comment]
Hyponyms.

Some APIs that give hyponyms for simple (non-compound) words are:
http://wordnet.princeton.edu/
https://www.wordsapi.com/
http://www.alchemyapi.com/products/demo/alchemylanguage  <- Some luck with compound words
