### ISSUE TITLE
Look into confirming entities via wikidata API before pushing to ES

### ISSUE THREAD

**Issue by eemp** [icwhatuc/auto-quiz-mill#6]
We can't simply push every single trending google search or NYT facet as we get it as an entity in our data store.  We need to confirm it against something like wikidata or a knowledge graph.  We should then store it with an identifier associated with that API.  This way we can avoid duplicates if there are 2 trending topics like "Barack Obama" and "Obama, Barack"

**Comment by icwhatuc** [comment]
Refer to the wiki page created for this for more details.

**Comment by eemp** [comment]
Already pushing wikidata entities out to Elasticsearch
